version: '3'
services:
  eureka:
    image: dudar/eureka-server:v1
    ports:
      - "8761:8761"
  config-server:
    image: dudar/config-server:v1
  gateway:
    image: dudar/gateway:v1
    ports:
      - "8082:8082"
  random-web:
    image: dudar/random-web:v1
